version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: reverseproxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/usr/share/nginx/html
      - ./conf.d/:/etc/nginx/conf.d
  nginx1:
    image: nginx:latest
    container_name: webserver1
    restart: unless-stopped
    ports:
      - 8000:80
      - 4000:443
    volumes:
      - ./src1:/usr/share/nginx/html
  nginx2:
    image: nginx:latest
    container_name: webserver2
    restart: unless-stopped
    ports:
      - 8100:80
      - 4100:443
    volumes:
      - ./src2:/usr/share/nginx/html
        
